// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ktuwjnjwnqwpcmcjqlii.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt0dXdqbmp3bnF3cGNtY2pxbGlpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxNTExODUsImV4cCI6MjA3MTcyNzE4NX0.eEpQEPfgVDD3Qq-jv84Dr9KjEZFdE3L9xybIaVKIzYg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});